### ISSUE TITLE
Unable to mount ext4 disk image

### ISSUE THREAD

**Issue by Gitborter** [alperakcan/fuse-ext2#31]
When I try to mount an ext4 disk image with fuse-ext2 I get an error 

$ sudo mount -t fuse-ext2 Downloads/diskimage.img /mnt/rasp

FUSE-EXT2 could not mount /dev/Downloads/diskimage.img
at /mnt/rasp because the following problem occurred:

Fuse expects the image to be in /dev rather than in the supplied location

I use fuse-ext2 0.0.9 running under OSX/ El Captain 10.11.3

**Comment by gpz500** [comment]
On Mac OS X, in order to mount a partition from a (raw) disk image file (or from a single-partition image file), you should "attach" the image file before (http://apple.stackexchange.com/questions/129921/how-to-mount-raw-disk-images) and then mount from the resulting /dev/disk* block device files.
After unmounting, you should too 'hdiutil detach'. See hdiutil online manual for help.

**Comment by Gitborter** [comment]
Thanks Allessandro,
Your solution works like a charm. By mounting the disk-image as raw partition I was able to mount it with fuse fuse-ext2 from /dev/disk....
