### ISSUE TITLE
configure fails: syntax error near unexpected token `e2fs,ext2fs'

### ISSUE THREAD

**Issue by stobenski** [alperakcan/fuse-ext2#35]
OS X 10.11.3 (15D21)
osxfuse-3.2.0 (same on osxfuse-2.8.3)

```
CFLAGS="-idirafter/$(brew --prefix e2fsprogs)/include -idirafter/usr/local/include/osxfuse" LDFLAGS="-L$(brew --prefix e2fsprogs)/lib" ./configure
```

```
checking for lseek64... no
checking for library containing sem_post... none required
checking for library containing fuse_main... -losxfuse
checking for library containing com_err... -lcom_err
checking for library containing ext2fs_open... -lext2fs
checking if FUSE on this system is too new for us... no
Disabling debug support by default
./configure: line 18606: syntax error near unexpected token `e2fs,ext2fs'
./configure: line 18606: `PKG_CHECK_MODULES(e2fs,ext2fs >= 1.41.13)'
```

```
~$ brew --prefix e2fsprogs

/usr/local/opt/e2fsprogs
```

```
~$ brew info e2fsprogs

e2fsprogs: stable 1.42.13 (bottled), HEAD [keg-only]
Utilities for the ext2, ext3, and ext4 file systems
http://e2fsprogs.sourceforge.net/
/usr/local/Cellar/e2fsprogs/1.42.13 (135 files, 5.0M)
  Poured from bottle
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/e2fsprogs.rb
==> Dependencies
Build: pkg-config ✔
Required: gettext ✔
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

This brew installs several commands which override OS X-provided file system commands.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/e2fsprogs/lib
    CPPFLAGS: -I/usr/local/opt/e2fsprogs/include
```

**Comment by barwinko** [comment]
Also,
```
export e2fs_CFLAGS=/usr/local/opt/e2fsprogs/lib
export e2fs_LIBS=/usr/local/opt/e2fsprogs/include
```
didn't help.

**Comment by barwinko** [comment]
After
```
export e2fs_CFLAGS=/usr/local/opt/e2fsprogs/lib
export e2fs_LIBS=/usr/local/opt/e2fsprogs/include
```
before ./autogen.sh making configure work fine. Thanks.

**Comment by barwinko** [comment]
After
```
export e2fs_CFLAGS=/usr/local/opt/e2fsprogs/lib
export e2fs_LIBS=/usr/local/opt/e2fsprogs/include
```
before ./autogen.sh making configure work fine. Thanks.

**Comment by KyleMay** [comment]
Why is this closed

**Comment by johannes87** [comment]
I still have this problem, the CFLAGS/LIBS exports make no difference.

**Comment by OdroidNStuff** [comment]
I have the exact same problem. Why is this closed?

**Comment by thecrackofdawn** [comment]
I solve this by following steps:
1. install pkg-config first
  `» brew install pkg-config`
2. run 
`» ./autogen.sh`
3. run 
`» PKG_CONFIG_PATH="$(brew --prefix e2fsprogs)/lib/pkgconfig" CFLAGS="-idirafter/$(brew --prefix e2fsprogs)/include -idirafter/usr/local/include/osxfuse" LDFLAGS="-L$(brew --prefix e2fsprogs)/lib" ./configure`

**Comment by simonegenovese** [comment]
I solve this by following steps:
1. install pkg-config first
» brew install pkg-config
2.  m4_ifdef([AM_PROG_AR], [AM_PROG_AR]) to the configure.ac file after m4_ifdef([AC_PROG_LIB],[AC_PROG_LIB],[m4_warn(portability,[Missing AC_PROJ_LIB])]).
3. run 
» ./autogen.sh
3. run 
» PKG_CONFIG_PATH="$(brew --prefix e2fsprogs)/lib/pkgconfig" CFLAGS="-idirafter/$(brew --prefix e2fsprogs)/include -idirafter/usr/local/include/osxfuse" LDFLAGS="-L$(brew --prefix e2fsprogs)/lib" ./configure

**Comment by preparationh67** [comment]
The above steps did not work for me, OSX El Captain 10.11.4

**Comment by kenti-lan** [comment]
@simonegenovese  Thanks a lot.It works!

**Comment by vss888** [comment]
I am having the same problem:

$ CFLAGS="-idirafter/opt/gnu/include -idirafter/usr/local/include/osxfuse/" LDFLAGS="-L/opt/gnu/lib -L/usr/local/lib" ./configure
./configure: line 18606: syntax error near unexpected token \`e2fs,ext2fs'
./configure: line 18606: \`PKG_CHECK_MODULES(e2fs,ext2fs >= 1.41.13)'

Solutions suggested by @thecrackofdawn and @simonegenovese do not work for me:

$ brew install pkg-config
/usr/local/bin/brew: line 28: /usr/local/Library/brew.rb: Permission denied
/usr/local/bin/brew: line 28: exec: /usr/local/Library/brew.rb: cannot execute: Undefined error: 0

$ sudo brew install pkg-config

produces the same error.

Could you please help?

**Comment by doughazell** [comment]
This may help someone in a similar position to me who comes here after a failed upgrade to Ubuntu 16.04 LTS due to https://wiki.ubuntu.com/1404_HWE_EOL.

'update-manager' stopped me from updating 14.04 due to https://wiki.ubuntu.com/1404_HWE_EOL

Then I tried command-line:
* $ sudo apt-get update
* $ sudo apt-get upgrade
* $ sudo apt-get dist-upgrade
* $ sudo do-release-upgrade

Now it won't boot...so I need to extract some files before reinstalling (backup a dev machine...nah...!!!)

I am still running:
```shell
Snow Leopard on MacBook5.1 
Env set up for Ruby on Rails dev (so don't want to change it)
```
  (the Ubuntu partition was to learn about Computer Vision and Neural Networks using ROS)

* $ brew --version
```shell
    Homebrew 1.0.9
    Homebrew/homebrew-core (git revision 6043; last commit 2016-11-04)
```
* Installed https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.5.3/osxfuse-3.5.3.dmg
* Attempted to follow Homebrew instructions on https://github.com/alperakcan/fuse-ext2
  * The 'm4' formula was changed to 'homebrew/dupes/m4'
  * When I got:

    ```shell
      ./configure: line 20616: syntax error near unexpected token `e2fs,ext2fs'
      ./configure: line 20616: `PKG_CHECK_MODULES(e2fs,ext2fs >= 1.41.13)'
    ```
  * then I commented out that line in 'configure'
  * but 'make' gave (on the linking phase):

    ```shell
      === BUILD NATIVE TARGET fuse-ext2 OF PROJECT fuse-ext2 WITH THE DEFAULT CONFIGURATION (Release) ===
      Check dependencies
      error: There is no SDK with the name or path 'macosx'
    ```
...prob because of my XCode SDK installation version (and env setup for Ruby on Rails dev)!

OK, plan B (after a lot of sighing and a cup of tea):
* Installed https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.5.3/osxfuse-3.5.3.dmg

  ```shell
    (done already)
  ```
* Install 'fuse-ext2-0.0.7.dmg' from https://sourceforge.net/projects/fuse-ext2/
* $ sudo fuse-ext2 /dev/disk0s3 ~/ubuntu/

...yay...:), now I can extract some ROS catkin + rosbuild C++ source + env cfg!

**Comment by alperakcan** [comment]
please follow readme.md for build instructions.
